[app_servers]
dsi1 ansible_host=192.168.123.121
dsi2 ansible_host=192.168.123.122
dsi3 ansible_host=192.168.123.123

[proxy]
proxy ansible_host=192.168.123.120

[all:vars]
ansible_user=tanver
ansible_ssh_private_key_file=~/.ssh/id_rsa
